database:
  host: postgres
  username: kdc_user
  password: kdc123456
  name: kdc_database
  port: 5432
  driver: postgres

redis:
  host: redis
  port: 6379
  password:
secret_key: uhbi49y823ry78923ijrgu803289u3ui23
RabbitMQURL: "amqp://admin:admin@pwd@127.0.0.1:5672/"

service:
  port: 80
  timeZone: "Asia/Phnom_Penh"
  logPtah: "logs/service-snap.log"
  http: true
  rabbitmq: false
  grcp: false

minio:
  Endpoint: "194.233.95.128:9000"
  AccessKeyID: "LDkJvmxsLZVg0PgbX1an"
  SecretAccessKey: "u24eGV04RcwPVss8iJ6GzTaunV867dwBwUxGf5qt"
  UseSSL: false
  MaxFileSize: 25485760 # 25MB
  Domain: "http://194.233.95.128:9000"

telegram:
  status: true
  account:
    - name: "Khdev"
      status: false
      apiHash: "xxxxx"
      appID: 123456789
      phoneNumber: "+855"
      sessionFile: "/app/session/myaccount.session"
  bots:
    - name: "Khdev_bot"
      status: false
      debug: false
      token: "xxxxxxxx"
      groupId: -4624244064
      back_button: true
github:
  client_id: "Ov23liBVXaZ0bV6B43Ut"
  client_secret: "28f9c091b494fc8bc1fd2b795c77be27b322f2c4"
  client_redir: "http://localhost:3000/api/auth02/github/callback"
  client_endpoint: "http://localhost:8080/"
