# Build stage
FROM golang:1.22.6 AS builder

WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Copy the config.yml file
COPY config/config.yml /app/config/config.yml

# Build the Go application with the specified binary name
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o product-service.bin .

# Final stage
FROM alpine:latest

WORKDIR /app



# Set the timezone to America/Bogota
# Install tzdata for timezone management
RUN apk add --no-cache tzdata
# Set the timezone
ENV TZ=Asia/Phnom_Penh
# Set the timezone data
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Copy the pre-built binary with the specified name from the previous stage
COPY --from=builder /app/product-service.bin .
COPY --from=builder /app/config/config.yml /app/config/config.yml

# Expose port 80 to the outside world
EXPOSE 80

# Command to run the executable
CMD ["./product-service.bin"]
